# Generated by Django 3.2.20 on 2023-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfacts',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
