# Generated by Django 4.2.4 on 2023-08-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_alter_mealrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecord',
            name='breakfast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='dinner',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='lunch',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='snack',
            field=models.TextField(blank=True),
        ),
    ]
